"""Add missing tables

Revision ID: 62b0e43f8a13
Revises: 27dde243ea1d
Create Date: 2026-03-06 10:38:18.010009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62b0e43f8a13'
down_revision: Union[str, Sequence[str], None] = '27dde243ea1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('session_type', sa.String(), nullable=True),
    sa.Column('bowling_type', sa.String(), nullable=True),
    sa.Column('filming_method', sa.String(), nullable=True),
    sa.Column('pitch_length', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_id'), 'sessions', ['id'], unique=False)
    op.create_index(op.f('ix_sessions_name'), 'sessions', ['name'], unique=False)
    op.create_table('deliveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('delivery_number', sa.Integer(), nullable=True),
    sa.Column('video_filename', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deliveries_id'), 'deliveries', ['id'], unique=False)
    op.create_table('analysis_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('delivery_id', sa.Integer(), nullable=False),
    sa.Column('speed', sa.Float(), nullable=True),
    sa.Column('line', sa.String(), nullable=True),
    sa.Column('length', sa.String(), nullable=True),
    sa.Column('swing', sa.Float(), nullable=True),
    sa.Column('pitchmap_x', sa.Float(), nullable=True),
    sa.Column('pitchmap_y', sa.Float(), nullable=True),
    sa.Column('release_point_x', sa.Float(), nullable=True),
    sa.Column('release_point_y', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['delivery_id'], ['deliveries.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('delivery_id')
    )
    op.create_index(op.f('ix_analysis_results_id'), 'analysis_results', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analysis_results_id'), table_name='analysis_results')
    op.drop_table('analysis_results')
    op.drop_index(op.f('ix_deliveries_id'), table_name='deliveries')
    op.drop_table('deliveries')
    op.drop_index(op.f('ix_sessions_name'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_id'), table_name='sessions')
    op.drop_table('sessions')
    # ### end Alembic commands ###
