"""Add run_up_speed and biomechanics

Revision ID: 7039121158dd
Revises: 62b0e43f8a13
Create Date: 2026-03-06 11:32:34.629345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7039121158dd'
down_revision: Union[str, Sequence[str], None] = '62b0e43f8a13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_results', sa.Column('run_up_speed', sa.Float(), nullable=True))
    op.add_column('analysis_results', sa.Column('biomechanics', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analysis_results', 'biomechanics')
    op.drop_column('analysis_results', 'run_up_speed')
    # ### end Alembic commands ###
